/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.personmanager;

import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;
import model.PersonDirectory;

/**
 *
 * @author Lakshman
 */
public class DashBoard extends javax.swing.JPanel {

	private PersonDirectory personDirectory;
	private JPanel mainFramePanel;

	/**
	 * Creates new form DashBoard
	 */
	public DashBoard(JPanel panel, PersonDirectory pd) {
		initComponents();
		mainFramePanel = panel;
		personDirectory = pd;
		
		setDashboardDetails();
	}
	
	public void setDashboardDetails() {
		HashMap<String, Integer> details = personDirectory.getDashboardDetails();
		
		count.setText(details.get("total_people") + "");
		marriedPeople.setText(details.get("married_count") + "");
		avgSalary.setText(details.get("avg_salary") + "");
		avgCreditScore.setText(details.get("avg_credit") + "");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        headingPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        totalPeoplePanel = new javax.swing.JPanel();
        heading1 = new javax.swing.JLabel();
        headingHelper1 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        dataOverviewPanel = new javax.swing.JPanel();
        heading2 = new javax.swing.JLabel();
        headingHelper2 = new javax.swing.JLabel();
        marriedPeopleLabel = new javax.swing.JLabel();
        avgSalaryLabel = new javax.swing.JLabel();
        avgCreditScoreLabel = new javax.swing.JLabel();
        marriedPeople = new javax.swing.JLabel();
        avgSalary = new javax.swing.JLabel();
        avgCreditScore = new javax.swing.JLabel();
        quickActionsPanel = new javax.swing.JPanel();
        heading3 = new javax.swing.JLabel();
        headingHelper3 = new javax.swing.JLabel();
        addPersonQuickBtn = new javax.swing.JButton();
        listPeopleQuickBtn = new javax.swing.JButton();

        splitPane.setDividerSize(0);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        headingPanel.setBackground(new java.awt.Color(255, 255, 255));
        headingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 240)));

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 0, 0));
        heading.setText("Dashboard");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(heading)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(heading)
                .addContainerGap())
        );

        splitPane.setTopComponent(headingPanel);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));

        totalPeoplePanel.setBackground(new java.awt.Color(255, 255, 255));
        totalPeoplePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 240), 2, true));
        totalPeoplePanel.setPreferredSize(new java.awt.Dimension(360, 200));

        heading1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heading1.setForeground(new java.awt.Color(0, 0, 0));
        heading1.setText("Total People");

        headingHelper1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        headingHelper1.setText("Number of people in the database");
        headingHelper1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        count.setBackground(new java.awt.Color(255, 255, 255));
        count.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        count.setForeground(new java.awt.Color(0, 0, 0));
        count.setText("0");

        javax.swing.GroupLayout totalPeoplePanelLayout = new javax.swing.GroupLayout(totalPeoplePanel);
        totalPeoplePanel.setLayout(totalPeoplePanelLayout);
        totalPeoplePanelLayout.setHorizontalGroup(
            totalPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPeoplePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(totalPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(count)
                    .addComponent(heading1)
                    .addComponent(headingHelper1))
                .addGap(114, 114, 114))
        );
        totalPeoplePanelLayout.setVerticalGroup(
            totalPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPeoplePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(heading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headingHelper1)
                .addGap(48, 48, 48)
                .addComponent(count)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        contentPanel.add(totalPeoplePanel);

        dataOverviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataOverviewPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 240), 2, true));
        dataOverviewPanel.setPreferredSize(new java.awt.Dimension(360, 200));

        heading2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heading2.setForeground(new java.awt.Color(0, 0, 0));
        heading2.setText("Data Overview");

        headingHelper2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        headingHelper2.setText("Summary of stored information");
        headingHelper2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        marriedPeopleLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        marriedPeopleLabel.setForeground(new java.awt.Color(0, 0, 0));
        marriedPeopleLabel.setText("Married People");

        avgSalaryLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        avgSalaryLabel.setForeground(new java.awt.Color(0, 0, 0));
        avgSalaryLabel.setText("Average Salary");

        avgCreditScoreLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        avgCreditScoreLabel.setForeground(new java.awt.Color(0, 0, 0));
        avgCreditScoreLabel.setText("Average Credit Score");

        marriedPeople.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        marriedPeople.setForeground(new java.awt.Color(0, 0, 0));
        marriedPeople.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        marriedPeople.setText("0");

        avgSalary.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        avgSalary.setForeground(new java.awt.Color(0, 0, 0));
        avgSalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avgSalary.setText("0");

        avgCreditScore.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        avgCreditScore.setForeground(new java.awt.Color(0, 0, 0));
        avgCreditScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avgCreditScore.setText("0");

        javax.swing.GroupLayout dataOverviewPanelLayout = new javax.swing.GroupLayout(dataOverviewPanel);
        dataOverviewPanel.setLayout(dataOverviewPanelLayout);
        dataOverviewPanelLayout.setHorizontalGroup(
            dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataOverviewPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataOverviewPanelLayout.createSequentialGroup()
                        .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heading2)
                            .addComponent(headingHelper2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataOverviewPanelLayout.createSequentialGroup()
                        .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgSalaryLabel)
                            .addComponent(marriedPeopleLabel)
                            .addComponent(avgCreditScoreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(avgCreditScore, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(marriedPeople, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(avgSalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        dataOverviewPanelLayout.setVerticalGroup(
            dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataOverviewPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(heading2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headingHelper2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marriedPeopleLabel)
                    .addComponent(marriedPeople))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgSalaryLabel)
                    .addComponent(avgSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgCreditScoreLabel)
                    .addComponent(avgCreditScore))
                .addGap(15, 15, 15))
        );

        contentPanel.add(dataOverviewPanel);

        quickActionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        quickActionsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 240), 2, true));
        quickActionsPanel.setPreferredSize(new java.awt.Dimension(360, 200));

        heading3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        heading3.setForeground(new java.awt.Color(0, 0, 0));
        heading3.setText("Quick Actions");

        headingHelper3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        headingHelper3.setText("Perform common tasks");
        headingHelper3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        addPersonQuickBtn.setBackground(new java.awt.Color(0, 0, 0));
        addPersonQuickBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addPersonQuickBtn.setForeground(new java.awt.Color(255, 255, 255));
        addPersonQuickBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user(2).png"))); // NOI18N
        addPersonQuickBtn.setText("Add Person");
        addPersonQuickBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonQuickBtnActionPerformed(evt);
            }
        });

        listPeopleQuickBtn.setBackground(new java.awt.Color(255, 255, 255));
        listPeopleQuickBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listPeopleQuickBtn.setForeground(new java.awt.Color(0, 0, 0));
        listPeopleQuickBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-groups(1).png"))); // NOI18N
        listPeopleQuickBtn.setText("View All");
        listPeopleQuickBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPeopleQuickBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quickActionsPanelLayout = new javax.swing.GroupLayout(quickActionsPanel);
        quickActionsPanel.setLayout(quickActionsPanelLayout);
        quickActionsPanelLayout.setHorizontalGroup(
            quickActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickActionsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(quickActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quickActionsPanelLayout.createSequentialGroup()
                        .addComponent(addPersonQuickBtn)
                        .addGap(18, 18, 18)
                        .addComponent(listPeopleQuickBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(heading3)
                    .addComponent(headingHelper3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        quickActionsPanelLayout.setVerticalGroup(
            quickActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickActionsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(heading3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headingHelper3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(quickActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPersonQuickBtn)
                    .addComponent(listPeopleQuickBtn))
                .addGap(34, 34, 34))
        );

        contentPanel.add(quickActionsPanel);

        splitPane.setRightComponent(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonQuickBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonQuickBtnActionPerformed
        // TODO add your handling code here:
	
	AddPerson panel = new AddPerson(mainFramePanel, personDirectory);
	mainFramePanel.add("AddPerson", panel);

	CardLayout layout = (CardLayout) mainFramePanel.getLayout();
	layout.next(mainFramePanel);
    }//GEN-LAST:event_addPersonQuickBtnActionPerformed

    private void listPeopleQuickBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPeopleQuickBtnActionPerformed
        // TODO add your handling code here:
        ListPerson panel = new ListPerson(mainFramePanel, personDirectory);
        mainFramePanel.add("ViewPerson", panel);

        CardLayout layout = (CardLayout) mainFramePanel.getLayout();
        layout.next(mainFramePanel);
    }//GEN-LAST:event_listPeopleQuickBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonQuickBtn;
    private javax.swing.JLabel avgCreditScore;
    private javax.swing.JLabel avgCreditScoreLabel;
    private javax.swing.JLabel avgSalary;
    private javax.swing.JLabel avgSalaryLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel count;
    private javax.swing.JPanel dataOverviewPanel;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel heading1;
    private javax.swing.JLabel heading2;
    private javax.swing.JLabel heading3;
    private javax.swing.JLabel headingHelper1;
    private javax.swing.JLabel headingHelper2;
    private javax.swing.JLabel headingHelper3;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JButton listPeopleQuickBtn;
    private javax.swing.JLabel marriedPeople;
    private javax.swing.JLabel marriedPeopleLabel;
    private javax.swing.JPanel quickActionsPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel totalPeoplePanel;
    // End of variables declaration//GEN-END:variables
}
