/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.personmanager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Lakshman
 */
public class ListPerson extends javax.swing.JPanel {
	
	private JPanel mainFramePanel;
	private PersonDirectory personDirectory;

	/**
	 * Creates new form ViewPerson
	 */
	public ListPerson(JPanel panel, PersonDirectory pd) {
		initComponents();
		personDirectory = pd;
		mainFramePanel = panel;
		
		populateTable();
	}
	
	public void populateTable() {
		DefaultTableModel model = (DefaultTableModel) peopleTable.getModel();
		model.setRowCount(0);
		
		for(Person person : personDirectory.getPersons()) {
			Object[] row = new Object[6];
			row[0] = person;
			row[1] = person.getLastName();
			row[2] = person.getHomeCity();
			row[3] = person.getHomeZipCode();
			row[4] = person.getWorkCity();
			row[5] = person.getWorkZipCode();
			
			model.addRow(row);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        splitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        formContainerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        viewSelectedPersonBtn = new javax.swing.JButton();
        deleteSelectedPersonBtn = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(255, 255, 255));

        splitPane.setDividerSize(0);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 240)));
        topPanel.setPreferredSize(new java.awt.Dimension(790, 100));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-arrow(1).png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 240)));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backBtn.setIconTextGap(5);
        backBtn.setMargin(new java.awt.Insets(10, 14, 3, 14));
        backBtn.setVerifyInputWhenFocusTarget(false);
        backBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 0, 0));
        heading.setText("People List");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heading))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        splitPane.setTopComponent(topPanel);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(790, 600));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10);
        flowLayout2.setAlignOnBaseline(true);
        mainPanel.setLayout(flowLayout2);

        formContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        formContainerPanel.setPreferredSize(new java.awt.Dimension(650, 550));

        peopleTable.setBackground(new java.awt.Color(255, 255, 255));
        peopleTable.setForeground(new java.awt.Color(0, 0, 0));
        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Home City", "Home Zip", "Work City", "Work Zip"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(peopleTable);

        viewSelectedPersonBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewSelectedPersonBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        viewSelectedPersonBtn.setForeground(new java.awt.Color(0, 0, 0));
        viewSelectedPersonBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view.png"))); // NOI18N
        viewSelectedPersonBtn.setText("View Selected");
        viewSelectedPersonBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        viewSelectedPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSelectedPersonBtnActionPerformed(evt);
            }
        });

        deleteSelectedPersonBtn.setBackground(new java.awt.Color(239, 68, 68));
        deleteSelectedPersonBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        deleteSelectedPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteSelectedPersonBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bin.png"))); // NOI18N
        deleteSelectedPersonBtn.setText("Delete Selected");
        deleteSelectedPersonBtn.setBorder(null);
        deleteSelectedPersonBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        deleteSelectedPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedPersonBtnActionPerformed(evt);
            }
        });

        searchBox.setBackground(new java.awt.Color(255, 255, 255));
        searchBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBox.setForeground(new java.awt.Color(0, 0, 0));
        searchBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 240), 2, true));

        searchBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(null);
        searchBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formContainerPanelLayout = new javax.swing.GroupLayout(formContainerPanel);
        formContainerPanel.setLayout(formContainerPanelLayout);
        formContainerPanelLayout.setHorizontalGroup(
            formContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(formContainerPanelLayout.createSequentialGroup()
                        .addComponent(viewSelectedPersonBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteSelectedPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        formContainerPanelLayout.setVerticalGroup(
            formContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formContainerPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(formContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewSelectedPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteSelectedPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBox)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        mainPanel.add(formContainerPanel);

        splitPane.setRightComponent(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
	mainFramePanel.remove(this);
		
	try {
		Component[] panelStack = mainFramePanel.getComponents();
		JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];

		DashBoard dashBoard = (DashBoard) lastPanel;
		dashBoard.setDashboardDetails();
	} catch (Exception e) {}

	CardLayout layout = (CardLayout) mainFramePanel.getLayout();
	layout.previous(mainFramePanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewSelectedPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSelectedPersonBtnActionPerformed
        // TODO add your handling code here:
	int selectedRow = peopleTable.getSelectedRow();
	
	if(selectedRow < 0) {
		JOptionPane.showMessageDialog(null,  "Please select a person from the list",  "Warning",  JOptionPane.WARNING_MESSAGE);
		return;
	}
	
	Person selectedAccount = (Person) peopleTable.getValueAt(selectedRow,  0);
	
	ViewPerson panel = new ViewPerson(mainFramePanel, personDirectory, selectedAccount);
	mainFramePanel.add("ViewAccountJPanel", panel);
	
	CardLayout layout = (CardLayout) mainFramePanel.getLayout();
	layout.next(mainFramePanel);
    }//GEN-LAST:event_viewSelectedPersonBtnActionPerformed

    private void deleteSelectedPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedPersonBtnActionPerformed
        // TODO add your handling code here:
	int selectedRow = peopleTable.getSelectedRow();
	
	if(selectedRow < 0) {
		JOptionPane.showMessageDialog(null,  "Please select a person from the list",  "Warning",  JOptionPane.WARNING_MESSAGE);
		return;
	}
	
	int dialogResult = JOptionPane.showConfirmDialog(null,  "Are you sure wante to delete the selected account?",  "Warning", JOptionPane.YES_NO_OPTION);
	if(dialogResult == JOptionPane.YES_OPTION) {
		Person selectedAccount = (Person) peopleTable.getValueAt(selectedRow,  0);
		personDirectory.removePerson(selectedAccount);
		populateTable();
	}
    }//GEN-LAST:event_deleteSelectedPersonBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
	String searchText = searchBox.getText();
	
	if(searchText.isBlank()) {
		JOptionPane.showMessageDialog(null,  "Please type the search text to view",  "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
	
	Person person = personDirectory.searchPerson(searchText);
	if(person == null) {
		JOptionPane.showMessageDialog(null,  "No Person found for given search text. Please try again.",  "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
	
	ViewPerson panel = new ViewPerson(mainFramePanel, personDirectory, person);
	mainFramePanel.add("ViewAccountJPanel", panel);
	CardLayout layout = (CardLayout) mainFramePanel.getLayout();
	layout.next(mainFramePanel);
	
	searchBox.setText("");
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteSelectedPersonBtn;
    private javax.swing.JPanel formContainerPanel;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable peopleTable;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchBtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewSelectedPersonBtn;
    // End of variables declaration//GEN-END:variables
}
