/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.personmanager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PersonDirectory;

/**
 *
 * @author Lakshman
 */
public class WelcomePage extends javax.swing.JPanel {

	private PersonDirectory personDirectory;
	private JPanel mainJPanel;
		
	/**
	 * Creates new form WelcomePage
	 */
	public WelcomePage(JPanel panel, PersonDirectory pd) {
		initComponents();
		mainJPanel = panel;
		personDirectory = pd;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        splitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        titleHelper = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        getStartedBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        splitPane.setDividerSize(0);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setPreferredSize(new java.awt.Dimension(1000, 700));

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 240)));
        topPanel.setForeground(new java.awt.Color(0, 0, 0));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 0, 0));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-groups.png"))); // NOI18N
        logo.setText("PersonManager");
        logo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(692, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(29, 29, 29))
        );

        splitPane.setTopComponent(topPanel);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 211));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        titleHelper.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        titleHelper.setForeground(new java.awt.Color(204, 204, 204));
        titleHelper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleHelper.setText("Easily store and manage personal information in one place.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 331;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        mainPanel.add(titleHelper, gridBagConstraints);

        title.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Welcome to PersonManager");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 439;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 6, 0, 6);
        mainPanel.add(title, gridBagConstraints);

        getStartedBtn.setBackground(new java.awt.Color(0, 0, 0));
        getStartedBtn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        getStartedBtn.setForeground(new java.awt.Color(255, 255, 255));
        getStartedBtn.setText("Get Started");
        getStartedBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getStartedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStartedBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 447, 389, 0);
        mainPanel.add(getStartedBtn, gridBagConstraints);

        splitPane.setRightComponent(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getStartedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStartedBtnActionPerformed
	MainPage mainPage = new MainPage(personDirectory);
	mainJPanel.add("MainPage", mainPage);
	
	CardLayout layout = (CardLayout) mainJPanel.getLayout();
	layout.next(mainJPanel);
    }//GEN-LAST:event_getStartedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getStartedBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleHelper;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
