/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.*;
import model.PersonDirectory;
import ui.personmanager.AddPerson;
import ui.personmanager.ListPerson;
/**
 *
 * @author Lakshman
 */
public class MainJFrame extends javax.swing.JFrame {

	private PersonDirectory personDirectory;
	
	/**
	 * Creates new form MainJFrame
	 */
	public MainJFrame() {
		initComponents();
		personDirectory = new PersonDirectory();		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        addPersonLabel = new javax.swing.JLabel();
        listPersonLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerSize(0);

        leftPanel.setBackground(new java.awt.Color(232, 232, 232));
        leftPanel.setPreferredSize(new java.awt.Dimension(210, 700));

        separator.setForeground(new java.awt.Color(204, 204, 204));

        title.setFont(new java.awt.Font("Calibri", 1, 21)); // NOI18N
        title.setForeground(new java.awt.Color(9, 9, 11));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-groups.png"))); // NOI18N
        title.setText("PersonManager");
        title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dashboardLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(121, 121, 130));
        dashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        dashboardLabel.setText("Dashboard");
        dashboardLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        addPersonLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addPersonLabel.setForeground(new java.awt.Color(121, 121, 130));
        addPersonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addPersonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user.png"))); // NOI18N
        addPersonLabel.setText("Add person");
        addPersonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPersonLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addPersonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPersonLabelMouseClicked(evt);
            }
        });

        listPersonLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        listPersonLabel.setForeground(new java.awt.Color(121, 121, 130));
        listPersonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listPersonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-groups-list.png"))); // NOI18N
        listPersonLabel.setText("List person");
        listPersonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listPersonLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listPersonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPersonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(43, 43, 43))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardLabel)
                    .addComponent(addPersonLabel)
                    .addComponent(listPersonLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPersonLabel)
                .addGap(12, 12, 12)
                .addComponent(listPersonLabel)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(leftPanel);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(790, 700));
        mainPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPersonLabelMouseClicked
        // TODO add your handling code here:
	AddPerson panel = new AddPerson(mainPanel, personDirectory);
	mainPanel.add("AddPerson", panel);
	
	CardLayout layout = (CardLayout) mainPanel.getLayout();
	layout.next(mainPanel);
    }//GEN-LAST:event_addPersonLabelMouseClicked

    private void listPersonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPersonLabelMouseClicked
        // TODO add your handling code here:
	ListPerson panel = new ListPerson(mainPanel, personDirectory);
	mainPanel.add("ViewPerson", panel);
	
	CardLayout layout = (CardLayout) mainPanel.getLayout();
	layout.next(mainPanel);
    }//GEN-LAST:event_listPersonLabelMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addPersonLabel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel listPersonLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSeparator separator;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
