/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.HashMap;
import javax.swing.JOptionPane;
import model.DeveloperProfile;

/**
 *
 * @author Lakshman
 */
public class CreateProfile extends javax.swing.JPanel {
	HashMap<String, DeveloperProfile> developers;

	/**
	 * Creates new form createProfile
	 */
	public CreateProfile(HashMap<String, DeveloperProfile> devs) {
		initComponents();
		developers = devs;
		mainScrollPanel.getVerticalScrollBar().setUnitIncrement(20); // Adjusting the scroll speed.
	}
	
	private boolean isEmpty(String field) {
		return field == null || field.trim().isEmpty();
	}

	private void showMessage(String message) {
		JOptionPane.showMessageDialog(null, message, "Field Validation", JOptionPane.WARNING_MESSAGE);
	}
	
	public  boolean isFormValid() {
		if (isEmpty(firstName.getText())) {
			showMessage("First Name is mandatory.");
			return false;
		}
		if (isEmpty(lastName.getText())) {
			showMessage("Last Name is mandatory.");
			return false;
		}
		if (isEmpty(username.getText())) {
			showMessage("Username is mandatory.");
			return false;
		}
		if(developers.containsKey(username.getText())) {
			showMessage("Username is already taken, please choose a new username!");
			return false;
		}
		if (isEmpty(email.getText())) {
			showMessage("Email is mandatory.");
			return false;
		}
		String emailPattern = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
		if(!email.getText().matches(emailPattern)) {
			showMessage("Enter a valid Email-ID");
			return false;
		}
		if (isEmpty(driverLicenseNo.getText())) {
			showMessage("Driver's License Number is mandatory.");
			return false;
		}
		if (isEmpty(driverLicenseState.getText())) {
			showMessage("Driver's License State is mandatory.");
			return false;
		}
		if (isEmpty(ssn.getText())) {
			showMessage("Social Security Number is mandatory.");
			return false;
		}
		if (isEmpty(linkedin.getText())) {
			showMessage("LinkedIn Profile is mandatory.");
			return false;
		}
		if (technicalSkills.getSelectedValuesList().isEmpty()) {
			showMessage("Technical Skills are mandatory.");
			return false;
		}
		if (areaOfInterest.getSelectedValuesList().isEmpty()) {
			showMessage("Area of Interest is mandatory.");
			return false;
		}

		// If all mandatory fields are filled
		return true;
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScrollPanel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        separater = new javax.swing.JSeparator();
        titleHelper = new javax.swing.JLabel();
        piSection = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        identificationSection = new javax.swing.JLabel();
        driverLicenseNoLabel = new javax.swing.JLabel();
        driverLicenseNo = new javax.swing.JTextField();
        driverLicenseStateLabel = new javax.swing.JLabel();
        driverLicenseState = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        ssn = new javax.swing.JTextField();
        addressLine1Label = new javax.swing.JLabel();
        addressLine1 = new javax.swing.JTextField();
        addressLine2 = new javax.swing.JTextField();
        addressLine2Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        zipCode = new javax.swing.JTextField();
        zipCodeLabel = new javax.swing.JLabel();
        piSection1 = new javax.swing.JLabel();
        contactInfoSection = new javax.swing.JLabel();
        telephoneNoLabel = new javax.swing.JLabel();
        telephoneNo = new javax.swing.JTextField();
        faxNo = new javax.swing.JTextField();
        faxNoLabel = new javax.swing.JLabel();
        professionalSection = new javax.swing.JLabel();
        technicalSkillsLabel = new javax.swing.JLabel();
        linkedin = new javax.swing.JTextField();
        linkedinLabel1 = new javax.swing.JLabel();
        yearsOfExp = new javax.swing.JSpinner();
        yearsOfExpLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        technicalSkills = new javax.swing.JList<>();
        professionalSummaryLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaOfInterest = new javax.swing.JList<>();
        areaOfInterestLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        professionalSummary = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();
        hidden = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setBackground(new java.awt.Color(44, 44, 45));

        mainScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(44, 44, 45));

        title.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Developer Information Form");

        titleHelper.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleHelper.setForeground(new java.awt.Color(234, 231, 231));
        titleHelper.setText("Please fill out all the required information");

        piSection.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        piSection.setForeground(new java.awt.Color(255, 255, 255));
        piSection.setText("<html><u>Personal Information");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(234, 231, 231));
        firstNameLabel.setText("First Name*");
        firstNameLabel.setToolTipText("Enter your first name.");

        firstName.setToolTipText("Enter your first name.");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(234, 231, 231));
        lastNameLabel.setText("Last Name*");
        lastNameLabel.setToolTipText("Enter your last name.");

        lastName.setToolTipText("Enter your last name.");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(234, 231, 231));
        emailLabel.setText("Email*");
        emailLabel.setToolTipText("Enter a valid email address.");

        email.setToolTipText("Enter a valid email address.");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(234, 231, 231));
        phoneLabel.setText("Phone");
        phoneLabel.setToolTipText("Enter your contact phone number.");

        phone.setToolTipText("Enter your contact phone number.");
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(234, 231, 231));
        dobLabel.setText("Date of Birth");
        dobLabel.setToolTipText("Enter your date of birth.");

        dob.setForeground(new java.awt.Color(204, 204, 204));
        dob.setToolTipText("Enter your date of birth.");
        dob.setFocusable(false);

        identificationSection.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        identificationSection.setForeground(new java.awt.Color(255, 255, 255));
        identificationSection.setText("<html><u>Address");

        driverLicenseNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverLicenseNoLabel.setForeground(new java.awt.Color(234, 231, 231));
        driverLicenseNoLabel.setText("Driver's License Number*");
        driverLicenseNoLabel.setToolTipText("Enter your driver's license number.");

        driverLicenseNo.setToolTipText("Enter your driver's license number.");
        driverLicenseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLicenseNoActionPerformed(evt);
            }
        });

        driverLicenseStateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverLicenseStateLabel.setForeground(new java.awt.Color(234, 231, 231));
        driverLicenseStateLabel.setText("Driver's License State*");
        driverLicenseStateLabel.setToolTipText("Enter the state where your driver's license was issued.");

        driverLicenseState.setForeground(new java.awt.Color(0, 0, 0));
        driverLicenseState.setToolTipText("Enter the state where your driver's license was issued.");
        driverLicenseState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLicenseStateActionPerformed(evt);
            }
        });

        ssnLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ssnLabel.setForeground(new java.awt.Color(234, 231, 231));
        ssnLabel.setText("Social Security Number*");
        ssnLabel.setToolTipText("Enter your social security number.");

        ssn.setToolTipText("Enter your social security number.");
        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });

        addressLine1Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLine1Label.setForeground(new java.awt.Color(234, 231, 231));
        addressLine1Label.setText("Address Line 1");
        addressLine1Label.setToolTipText("Enter your primary street address.");

        addressLine1.setToolTipText("Enter your primary street address.");
        addressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1ActionPerformed(evt);
            }
        });

        addressLine2.setToolTipText("Enter your secondary address (e.g., apartment or suite number).");
        addressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine2ActionPerformed(evt);
            }
        });

        addressLine2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLine2Label.setForeground(new java.awt.Color(234, 231, 231));
        addressLine2Label.setText("Address Line 2");
        addressLine2Label.setToolTipText("Enter your secondary address (e.g., apartment or suite number).");

        cityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(234, 231, 231));
        cityLabel.setText("City");
        cityLabel.setToolTipText("Enter your city.");

        city.setToolTipText("Enter your city.");
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        stateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateLabel.setForeground(new java.awt.Color(234, 231, 231));
        stateLabel.setText("State");
        stateLabel.setToolTipText("Enter your state.");

        state.setToolTipText("Enter your state.");
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });

        zipCode.setToolTipText("Enter your ZIP code.");
        zipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeActionPerformed(evt);
            }
        });

        zipCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zipCodeLabel.setForeground(new java.awt.Color(234, 231, 231));
        zipCodeLabel.setText("ZIP Code");
        zipCodeLabel.setToolTipText("Enter your ZIP code.");

        piSection1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        piSection1.setForeground(new java.awt.Color(255, 255, 255));
        piSection1.setText("<html><u>Identification");

        contactInfoSection.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        contactInfoSection.setForeground(new java.awt.Color(255, 255, 255));
        contactInfoSection.setText("<html><u>Contact Information");

        telephoneNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telephoneNoLabel.setForeground(new java.awt.Color(234, 231, 231));
        telephoneNoLabel.setText("Telephone Number");
        telephoneNoLabel.setToolTipText("Enter your telephone number.");

        telephoneNo.setToolTipText("Enter your telephone number.");
        telephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNoActionPerformed(evt);
            }
        });

        faxNo.setToolTipText("Enter your fax number.");
        faxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxNoActionPerformed(evt);
            }
        });

        faxNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        faxNoLabel.setForeground(new java.awt.Color(234, 231, 231));
        faxNoLabel.setText("Fax Number");
        faxNoLabel.setToolTipText("Enter your fax number.");

        professionalSection.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        professionalSection.setForeground(new java.awt.Color(255, 255, 255));
        professionalSection.setText("<html><u>Professional Information");

        technicalSkillsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        technicalSkillsLabel.setForeground(new java.awt.Color(234, 231, 231));
        technicalSkillsLabel.setText("Technical Skills*");
        technicalSkillsLabel.setToolTipText("Select all the technical skills you posses.");

        linkedin.setToolTipText("Enter the URL of your LinkedIn profile.");
        linkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedinActionPerformed(evt);
            }
        });

        linkedinLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkedinLabel1.setForeground(new java.awt.Color(234, 231, 231));
        linkedinLabel1.setText("LinkedIn Profile*");
        linkedinLabel1.setToolTipText("Enter the URL of your LinkedIn profile.");

        yearsOfExp.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        yearsOfExp.setToolTipText("Enter your years of professional experience.");

        yearsOfExpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearsOfExpLabel.setForeground(new java.awt.Color(234, 231, 231));
        yearsOfExpLabel.setText("Years of Experience");
        yearsOfExpLabel.setToolTipText("Enter your years of professional experience.");

        technicalSkills.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Python (Programming Language)", "Java (Programming Language)", "JavaScript (Web Development)", "SQL (Database Management)", "Amazon Web Services (AWS) (Cloud Computing)", "Docker (Containerization)", "Git (Version Control)", "Linux (Operating System)", "React.js (Frontend Web Development)", "Node.js (Backend Web Development)", "Kubernetes (Container Orchestration)", "TensorFlow (Machine Learning/AI)", "Selenium (Software Testing Automation)", "MySQL (Database Management)", "Jenkins (CI/CD & DevOps)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        technicalSkills.setToolTipText("Select all the technical skills you posses");
        jScrollPane2.setViewportView(technicalSkills);

        professionalSummaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        professionalSummaryLabel.setForeground(new java.awt.Color(234, 231, 231));
        professionalSummaryLabel.setText("Professional Summary");
        professionalSummaryLabel.setToolTipText("Summarize your professional experience.");

        areaOfInterest.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Artificial Intelligence (AI) and Machine Learning (ML)", "Data Science and Analytics", "Cloud Computing", "Cybersecurity", "Blockchain Technology", "Internet of Things (IoT)", "Web Development", "Mobile App Development", "Augmented Reality (AR) and Virtual Reality (VR)", "Quantum Computing", "Game Development", "Robotics and Automation", "UI/UX Design", "Digital Marketing", "Sustainable and Green Technology" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        areaOfInterest.setToolTipText("Select you area of interest.");
        jScrollPane3.setViewportView(areaOfInterest);

        areaOfInterestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaOfInterestLabel.setForeground(new java.awt.Color(234, 231, 231));
        areaOfInterestLabel.setText("Areas of Interest*");
        areaOfInterestLabel.setToolTipText("Select you area of interest.");

        professionalSummary.setColumns(20);
        professionalSummary.setRows(5);
        professionalSummary.setToolTipText("Summarize your professional experience.");
        jScrollPane1.setViewportView(professionalSummary);

        submitBtn.setBackground(new java.awt.Color(122, 79, 240));
        submitBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        hidden.setText(" ");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(234, 231, 231));
        usernameLabel.setText("Username*");
        usernameLabel.setToolTipText("Choose a unique username.");

        username.setToolTipText("Choose a unique username.");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleHelper, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(piSection)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstName)
                        .addGap(20, 20, 20)
                        .addComponent(lastName)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(281, 281, 281))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(281, 281, 281))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(email)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(281, 281, 281))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phone)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(281, 281, 281))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(piSection1)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(driverLicenseNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(driverLicenseStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(driverLicenseNo)
                        .addGap(21, 21, 21)
                        .addComponent(driverLicenseState))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ssnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ssn)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(identificationSection)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLine1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLine1)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLine2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLine2)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(city)
                        .addGap(21, 21, 21)
                        .addComponent(state))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(zipCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(zipCode)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contactInfoSection)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telephoneNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telephoneNo)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(faxNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(faxNo)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(professionalSection)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(linkedinLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(linkedin)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearsOfExpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearsOfExp)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(technicalSkillsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(areaOfInterestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(professionalSummaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(131, 131, 131))
                    .addComponent(hidden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addComponent(separater)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(titleHelper, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(separater, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(piSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName))
                .addGap(8, 8, 8)
                .addComponent(usernameLabel)
                .addGap(0, 0, 0)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(emailLabel)
                .addGap(0, 0, 0)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(phoneLabel)
                .addGap(0, 0, 0)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(dobLabel)
                .addGap(0, 0, 0)
                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(piSection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverLicenseNoLabel)
                    .addComponent(driverLicenseStateLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLicenseState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(ssnLabel)
                .addGap(0, 0, 0)
                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(identificationSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(addressLine1Label)
                .addGap(0, 0, 0)
                .addComponent(addressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(addressLine2Label)
                .addGap(0, 0, 0)
                .addComponent(addressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel)
                    .addComponent(stateLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(zipCodeLabel)
                .addGap(0, 0, 0)
                .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(contactInfoSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(telephoneNoLabel)
                .addGap(0, 0, 0)
                .addComponent(telephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(faxNoLabel)
                .addGap(0, 0, 0)
                .addComponent(faxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(professionalSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(linkedinLabel1)
                .addGap(0, 0, 0)
                .addComponent(linkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(yearsOfExpLabel)
                .addGap(0, 0, 0)
                .addComponent(yearsOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(technicalSkillsLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(areaOfInterestLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(professionalSummaryLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(hidden)
                .addContainerGap())
        );

        mainScrollPanel.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void driverLicenseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLicenseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverLicenseNoActionPerformed

    private void driverLicenseStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLicenseStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverLicenseStateActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed

    private void addressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine1ActionPerformed

    private void addressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine2ActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void zipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeActionPerformed

    private void telephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNoActionPerformed

    private void faxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxNoActionPerformed

    private void linkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkedinActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
	//Form validation for mandatory fields
	if(!isFormValid()) {
		return;
	}
	
	DeveloperProfile dev = new DeveloperProfile();
	
	// Personal Information
	dev.setFirstName(firstName.getText());
	dev.setLastName(lastName.getText());
	dev.setUserName(username.getText());
	dev.setEmail(email.getText());
	dev.setPhone(phone.getText());
	dev.setDateOfBirth(dob.getDate());
	
	// Identification details
	dev.setDriversLicenseNumber(driverLicenseNo.getText());
	dev.setDriversLicenseState(driverLicenseState.getText());
	dev.setSocialSecurityNumber(ssn.getText());
	
	//Address Details
	dev.setAddressLine1(addressLine1.getText());
	dev.setAddressLine2(addressLine2.getText());
	dev.setCity(city.getText());
	dev.setState(state.getText());
	dev.setZip(zipCode.getText());
	
	//Contact Information
	dev.setTelephoneNumber(telephoneNo.getText());
	dev.setFaxNumber(faxNo.getText());
	
	//Professional Information
	dev.setLinkedInProfile(linkedin.getText());
	dev.setYearsOfExperience((int) yearsOfExp.getValue());
	dev.setTechnicalSkills(technicalSkills.getSelectedValuesList());
	dev.setTechnicalSkillsIndices(technicalSkills.getSelectedIndices());
	dev.setAreaOfInterest(areaOfInterest.getSelectedValuesList());
	dev.setAreaOfInterestIndices(areaOfInterest.getSelectedIndices());
	dev.setProfessionalSummary(professionalSummary.getText());
	
	developers.put(username.getText(), dev);
	
	JOptionPane.showMessageDialog(this, "Developer information saved successfully!", "Form Saved", JOptionPane.INFORMATION_MESSAGE);
	
	//Clear fields
	firstName.setText("");
	lastName.setText("");
	username.setText("");
	email.setText("");
	phone.setText("");
	dob.setDate(null);
	driverLicenseNo.setText("");
	driverLicenseState.setText("");
	ssn.setText("");
	addressLine1.setText("");
	addressLine2.setText("");
	city.setText("");
	state.setText("");
	zipCode.setText("");
	telephoneNo.setText("");
	faxNo.setText("");
	linkedin.setText("");
	yearsOfExp.setValue(0);
	technicalSkills.clearSelection();
	areaOfInterest.clearSelection();
	professionalSummary.setText("");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressLine1;
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JTextField addressLine2;
    private javax.swing.JLabel addressLine2Label;
    private javax.swing.JList<String> areaOfInterest;
    private javax.swing.JLabel areaOfInterestLabel;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel contactInfoSection;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField driverLicenseNo;
    private javax.swing.JLabel driverLicenseNoLabel;
    private javax.swing.JTextField driverLicenseState;
    private javax.swing.JLabel driverLicenseStateLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField faxNo;
    private javax.swing.JLabel faxNoLabel;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel identificationSection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField linkedin;
    private javax.swing.JLabel linkedinLabel1;
    private javax.swing.JScrollPane mainScrollPanel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel piSection;
    private javax.swing.JLabel piSection1;
    private javax.swing.JLabel professionalSection;
    private javax.swing.JTextArea professionalSummary;
    private javax.swing.JLabel professionalSummaryLabel;
    private javax.swing.JSeparator separater;
    private javax.swing.JTextField ssn;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField state;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JList<String> technicalSkills;
    private javax.swing.JLabel technicalSkillsLabel;
    private javax.swing.JTextField telephoneNo;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleHelper;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JSpinner yearsOfExp;
    private javax.swing.JLabel yearsOfExpLabel;
    private javax.swing.JTextField zipCode;
    private javax.swing.JLabel zipCodeLabel;
    // End of variables declaration//GEN-END:variables
}
